Freeze package.version in kongfig executable with Babel plugin
adhocteam/kongfig pull request #31
Opened 2019-11-08 19:36 UTC by mjlumetta

https://github.com/department-of-veterans-affairs/vets-contrib/issues/3563

instead of requiring `package.json` in the `cli` module and using `package.version` for the kongfig version, this uses a special variable `__VERSION__` which [`babel-plugin-version`](https://www.npmjs.com/package/babel-plugin-version) compiles to the value of `package.version` at build time.

therefore, the following should all return the same version:

```
~$ kongfig --version
~/kongfig$ bin/kongfig --version
```

my compiled `lib/cli.js` (with spacing):

```
"use strict";

var _commander = require("commander");

var _commander2 = _interopRequireDefault(_commander);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

_commander2.default.version("3.0.1")
  .allowUnknownOption()
  .command('apply', 'Apply config to a kong server', {
    isDefault: true
  })
  .command('dump', 'Dump the configuration from a kong server')
  .command('prune', 'Rewrites config omitting any service, route, global plugin or service/route plugin marked "ensure: removed"')
  .parse(process.argv);
```

2019-11-08 20:41 UTC, jasalisbury approved these changes
This LGTM, but I've been thinking about how this is going to work once released and other teams are running it against Kong... Even with this change it will still be possible for someone to pull down kongfig, forget to build it and run it successfully (successful as in passes the version check in `kong_sync`) against Kong. This is my first thought, may be a better way; We may need to add another command to kongfig (`kongfig version`) that uses this new version explicitly and update `kong_sync` to use the new command. This would prevent an engineer from pulling the new version of kongfig and running it against Kong without building kongfig first.

2019-11-08 20:42 UTC, mjlumetta commented
@jasalisbury `kongfig [--]required-version`?

2019-11-08 20:55 UTC, jasalisbury commented
> @jasalisbury `kongfig [--]required-version`?

I don't think `required` should be in the name... Honestly it is more like `built-version` or `compiled-version`. I'd probably prefer `version` out of all of them though.

2019-11-08 21:15 UTC, mjlumetta commented
oh right, it's currently only with the option. yes, i'll do that

2019-11-11 16:48 UTC, kalilsn requested changes
There's a second `version` command defined in cli-apply: https://github.com/adhocteam/kongfig/blob/master/src/cli-apply.js#L14. I'm not clear on which one takes precedence – could you either eliminate one or update both?

2019-11-11 16:59 UTC, kalilsn commented
@jasalisbury To make sure we're on the same page: your objection is that even if we require `3.0.1`, someone who has an old version of kongfig built locally will still pass the `kong_sync` version check just by pulling from the remote repo, since their kongfig will still use the old `--version` command?

Switching to a slightly different command (here and in `./kong_sync`) would fix that, as would instituting a real release process.

We could also change our approach a bit: instead of using package.json as the source of truth we could read from a different file. Then we could leave package.json alone, and the old version check wouldn't report 3.0.1. To do that we'd need our own version babel plugin, but they seem pretty simple: https://github.com/gnandretta/babel-plugin-version-inline/blob/master/src/index.js

2019-11-11 17:18 UTC, jasalisbury commented
> @jasalisbury To make sure we're on the same page: your objection is that even if we require `3.0.1`, someone who has an old version of kongfig built locally will still pass the `kong_sync` version check just by pulling from the remote repo, since their kongfig will still use the old `--version` command?

Yeah that is my concern

> Switching to a slightly different command (here and in `./kong_sync`) would fix that, as would instituting a real release process.
> 
> We could also change our approach a bit: instead of using package.json as the source of truth we could read from a different file. Then we could leave package.json alone, and the old version check wouldn't report 3.0.1. To do that we'd need our own version babel plugin, but they seem pretty simple: https://github.com/gnandretta/babel-plugin-version-inline/blob/master/src/index.js

I thought about that as well, I'm pretty sure I found a plugin that let you set the version manually instead of using `package.json`. My main concern with using a version outside of `package.json` is keeping the two versions in sync, one in `package.json` and the other in the new plugin config. Maybe we wouldn't need to use the `package.json` version if we had the plugin. However `package.json` seems to be the common place to set the version of the package and I'd hate to lose unless we really need ot.

2019-11-11 17:35 UTC, kalilsn commented
> My main concern with using a version outside of package.json is keeping the two versions in sync, one in package.json and the other in the new plugin config. Maybe we wouldn't need to use the package.json version if we had the plugin. However package.json seems to be the common place to set the version of the package and I'd hate to lose unless we really need ot.

Yeah, that's not great. In my mind, this would only be a temporary change, and we'd go back to using package.json once we have a real release process. I'm still not convinced it's a good idea, just thought I would mention it :)

2019-11-11 19:08 UTC, mjlumetta commented
@jasalisbury @kalilsn i think what i'm going to do for the new version command is add a new alias for `--version` (see [here](https://github.com/tj/commander.js#version-option)). it's not particularly great from a naming perspective, but it addresses the requirement and continues to use the functionality of the CLI, and if it is actually temporary as Kalil says, then maybe it's okay? i'll use one of the names Josh suggested above, i guess. i would also potentially consider a worse name that highlights the problem it is solving, like `--true-version` or `--real-version`, if we are sure that we're going to prioritize a real release process. but will default to `compiled` or `build`

2019-11-11 19:21 UTC, kalilsn approved these changes

2019-11-11 19:29 UTC, merged

2019-11-11 19:30 UTC, jasalisbury commented
> @jasalisbury @kalilsn i think what i'm going to do for the new version command is add a new alias for `--version` (see [here](https://github.com/tj/commander.js#version-option)). it's not particularly great from a naming perspective, but it addresses the requirement and continues to use the functionality of the CLI, and if it is actually temporary as Kalil says, then maybe it's okay? i'll use one of the names Josh suggested above, i guess. i would also potentially consider a worse name that highlights the problem it is solving, like `--true-version` or `--real-version`, if we are sure that we're going to prioritize a real release process. but will default to `compiled` or `build`

This is going to be paired with an update to `kong_sync` that uses `--compiled-version` instead of `--version`?

2019-11-11 19:33 UTC, mjlumetta commented
@jasalisbury i had trouble getting the long option to work correctly for some reason, but `-v` is different from the default (`-V`) so going to use that. again, also not great, but will work. but in answer to your actual question, yes, pushing it up now!

2019-11-11 19:46 UTC, mjlumetta commented
actually - i think there's a slight nuance that i missed here, so i'm going to follow up with another PR. for the `kong_sync` check to work, it has to error out on the unknown option. which means a couple things:

1. `--version` can't be a known option, so going to have to return to that
2. in order to check for a `kongfig` failure, we need config to exit with a non-zero status, specifically for `kongfig --version`. i think that means removing [this line](https://github.com/adhocteam/kongfig/blob/master/src/cli.js#L5) and specifying allowed options here. 

anyway, don't think this is a downgrade as-is. going to step out to grab coffee, lmk what your thoughts are