Fix integration tests
adhocteam/kongfig pull request #9
Opened 2019-07-05 18:16 UTC by kalilsn

Preliminary work for https://github.com/department-of-veterans-affairs/vets-contrib/issues/2492

The integration tests are now runnable with `npm run test-integration`. The snapshots can be updated with `npm run test-integration -- -u`. You'll need a local kong instance running on port 8001, which I was able to achieve with https://github.com/Kong/docker-kong/tree/master/compose. In order to run this with 0.14.1, I first had to change the `kong_migrations` service's command to `kong migrations up`, then ran `KONG_DOCKER_TAG=kong:0.14.1 docker-compose up`.

2019-07-05 18:19 UTC, dvogel commented
Is the `ssl_certificate` -> `certificate` change breaking backward compatibility?

2019-07-05 18:21 UTC, kalilsn commented
> Is the ssl_certificate -> certificate change breaking backward compatibility?

Yes, it's breaking compatibility with 0.13 and earlier, in order to fix compatibility with 0.14 onwards, which we're currently using.

2019-07-05 18:26 UTC, dvogel requested changes
> > Is the ssl_certificate -> certificate change breaking backward compatibility?
> 
> Yes, it's breaking compatibility with 0.13 and earlier, in order to fix compatibility with 0.14 onwards, which we're currently using.

:+1: Can you make sure this change in version compatibility is reflected in the README?

2019-07-09 13:30 UTC, dvogel approved these changes

2019-07-09 14:26 UTC, jasalisbury approved these changes

2019-07-09 15:15 UTC, merged